name: Build Docker images

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
     
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push nginx-proxy Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: .
          file: Dockerfile.alpine
          tags: florianpiesche/nginx-proxy-arm:latest
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: true
